### PR TITLE
Basic quad rendering with shaders

### PR DESCRIPTION
**Pull request by vtboy2000**

### CODE REVIEW

**Comment by Rmarmorstein** [comment]
Thank you - Please see the CI Build for details. The build failed for a few different reasons.

Once these are fixed, I'll be happy to merge this in. Thanks

**Comment by vtboy2000** [comment]
Finally merged with master, and updated it with my code.

**Comment by vtboy2000** [comment]
documentation added, and general cleaning up

**Comment by vtboy2000** [comment]
documentation, and general cleaning up.

**Pull request merged**
